//receives a string of date generated by new date() and returns date and hour separatly

export const dateSplitter = (time: any) => {
  let date = time.split("T")[0];
  let hour = time.split("T")[1].split(".")[0];
  return `${date} at ${hour}`;
};
